# Generated by Django 3.2.9 on 2022-01-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('synopsis', models.TextField()),
                ('project_cover', models.ImageField(upload_to='map/project_cover')),
                ('draft_password', models.CharField(blank=True, max_length=30, null=True)),
                ('url_map', models.CharField(blank=True, max_length=50, null=True)),
                ('title_seo', models.CharField(blank=True, max_length=50, null=True)),
                ('description_seo', models.CharField(blank=True, max_length=50, null=True)),
                ('site_name_seo', models.CharField(blank=True, max_length=50, null=True)),
                ('image_seo', models.ImageField(blank=True, null=True, upload_to='map/image_seo')),
            ],
            options={
                'verbose_name': 'Mapa',
            },
        ),
    ]
