# Generated by Django 4.0.1 on 2022-01-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('node_color', models.CharField(max_length=255, verbose_name='Cor do nó')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('min_size', models.FloatField(blank=True, null=True, verbose_name='Tamanho mínimo')),
                ('max_size', models.FloatField(blank=True, null=True, verbose_name='Tamanho máximo')),
                ('height_area', models.FloatField(blank=True, null=True, verbose_name='Altura da área')),
                ('show', models.BooleanField(default=True, verbose_name='Exibir')),
            ],
            options={
                'verbose_name': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('label', models.CharField(max_length=255, verbose_name='Rótulo')),
                ('text', models.TextField(verbose_name='Texto')),
                ('x_position', models.FloatField(blank=True, null=True, verbose_name='Posição X')),
                ('y_position', models.FloatField(blank=True, null=True, verbose_name='Posição Y')),
                ('namespace', models.CharField(blank=True, max_length=255, null=True)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('button_icon', models.FileField(blank=True, null=True, upload_to='node/button_icon', verbose_name='Ícone do botão')),
                ('button_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto do botão')),
                ('button_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link do botão')),
            ],
            options={
                'verbose_name': 'Nó',
            },
        ),
        migrations.AlterField(
            model_name='map',
            name='description_seo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição SEO'),
        ),
        migrations.AlterField(
            model_name='map',
            name='draft_password',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Senha de rascunho'),
        ),
        migrations.AlterField(
            model_name='map',
            name='image_seo',
            field=models.ImageField(blank=True, null=True, upload_to='map/image_seo', verbose_name='Imagem SEO'),
        ),
        migrations.AlterField(
            model_name='map',
            name='project_cover',
            field=models.ImageField(upload_to='map/project_cover', verbose_name='Capa do projeto'),
        ),
        migrations.AlterField(
            model_name='map',
            name='site_name_seo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do site SEO'),
        ),
        migrations.AlterField(
            model_name='map',
            name='synopsis',
            field=models.TextField(verbose_name='Sinopse'),
        ),
        migrations.AlterField(
            model_name='map',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='map',
            name='title_seo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Título SEO'),
        ),
        migrations.AlterField(
            model_name='map',
            name='url_map',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='URL do mapa'),
        ),
    ]
