# Generated by Django 3.2.9 on 2022-01-13 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_category_node_alter_map_description_seo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='map',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='map.map', verbose_name='Mapa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='nodes',
            field=models.ManyToManyField(blank=True, related_name='categories', to='map.Node', verbose_name='Nós'),
        ),
        migrations.CreateModel(
            name='NodeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contexto')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_mappings', to='map.map', verbose_name='Mapa')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_mappings', to='map.node', verbose_name='Nó de origem')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_mappings', to='map.node', verbose_name='Nó de destino')),
            ],
            options={
                'verbose_name': 'Mapeamento de nós',
            },
        ),
    ]
