# Generated by Django 3.2.9 on 2022-01-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20220113_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nodemapping',
            options={'verbose_name': 'Mapeamento de nós', 'verbose_name_plural': 'Mapeamentos de nós'},
        ),
        migrations.AlterField(
            model_name='map',
            name='description_seo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição SEO'),
        ),
        migrations.AlterField(
            model_name='map',
            name='draft_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Senha de rascunho'),
        ),
        migrations.AlterField(
            model_name='map',
            name='site_name_seo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do site SEO'),
        ),
        migrations.AlterField(
            model_name='map',
            name='title_seo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título SEO'),
        ),
        migrations.AlterField(
            model_name='map',
            name='url_map',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL do mapa'),
        ),
    ]
