# Generated by Django 3.2.9 on 2022-01-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20220113_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ordem'),
        ),
    ]
