# Generated by Django 3.2.9 on 2022-01-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Texto'),
        ),
    ]
