# Generated by Django 3.2.9 on 2022-01-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_alter_node_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID antigo'),
        ),
    ]
