# Generated by Django 3.2.9 on 2022-01-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_node__id'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='summary',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Resumo'),
        ),
    ]
