# Generated by Django 4.0.1 on 2022-01-25 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_map_editors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Camada'},
        ),
    ]
