# Generated by Django 4.0.1 on 2022-01-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Exibir'),
        ),
    ]
